namespace EU4SaveAnalyzer.Services;

/// <summary>
/// Statisches Mapping von EU4 Länder-Tags zu Ländernamen.
/// Fallback wenn der Name nicht im Save-File steht.
/// </summary>
public static class EU4TagNames
{
    public static string GetName(string tag)
    {
        if (string.IsNullOrEmpty(tag)) return tag;
        return _names.TryGetValue(tag.ToUpperInvariant(), out var name) ? name : tag;
    }

    private static readonly Dictionary<string, string> _names =
        new(StringComparer.OrdinalIgnoreCase)
    {
        // Europa West
        {"FRA", "Frankreich"},
        {"ENG", "England"},
        {"GBR", "Großbritannien"},
        {"CAS", "Kastilien"},
        {"SPA", "Spanien"},
        {"POR", "Portugal"},
        {"ARA", "Aragon"},
        {"NAV", "Navarra"},
        {"GRA", "Granada"},
        {"SCO", "Schottland"},
        {"IRE", "Irland"},
        {"BRT", "Bretagne"},
        {"BUR", "Burgund"},
        {"PRO", "Provence"},
        {"SAV", "Savoyen"},
        {"GEN", "Genua"},
        {"VEN", "Venedig"},
        {"MIL", "Mailand"},
        {"NAP", "Neapel"},
        {"SIC", "Sizilien"},
        {"PAP", "Kirchenstaat"},
        {"FLO", "Florenz"},
        {"TUS", "Toskana"},
        {"MOD", "Modena"},
        {"MAN", "Mantua"},
        {"FER", "Ferrara"},
        {"SIE", "Siena"},
        {"LUC", "Lucca"},
        {"URB", "Urbino"},
        {"RAG", "Ragusa"},

        // Heiliges Römisches Reich
        {"HRE", "Heiliges Römisches Reich"},
        {"AUS", "Österreich"},
        {"HAB", "Habsburg"},
        {"PRU", "Preußen"},
        {"BRA", "Brandenburg"},
        {"SAX", "Sachsen"},
        {"BAV", "Bayern"},
        {"SWI", "Schweiz"},
        {"TYR", "Tirol"},
        {"STY", "Steiermark"},
        {"BOH", "Böhmen"},
        {"MOR", "Mähren"},
        {"SIL", "Schlesien"},
        {"PAL", "Pfalz"},
        {"TRI", "Trier"},
        {"COL", "Köln"},
        {"MAI", "Mainz"},
        {"MEC", "Mecklenburg"},
        {"POM", "Pommern"},
        {"WUR", "Württemberg"},
        {"BAD", "Baden"},
        {"HES", "Hessen"},
        {"THU", "Thüringen"},
        {"ANS", "Ansbach"},
        {"OLD", "Oldenburg"},
        {"MUN", "Münster"},
        {"LUN", "Lüneburg"},
        {"MAG", "Magdeburg"},
        {"HAM", "Hamburg"},
        {"LUB", "Lübeck"},
        {"BRE", "Bremen"},
        {"NUR", "Nürnberg"},
        {"ULM", "Ulm"},
        {"AUG", "Augsburg"},
        {"STR", "Straßburg"},
        {"LOT", "Lothringen"},
        {"LUX", "Luxemburg"},
        {"FRI", "Friesland"},
        {"HOL", "Holland"},
        {"ZEA", "Zeeland"},
        {"UTR", "Utrecht"},
        {"GEL", "Geldern"},
        {"FLA", "Flandern"},
        {"NET", "Niederlande"},

        // Nord-Europa
        {"DAN", "Dänemark"},
        {"SWE", "Schweden"},
        {"NOR", "Norwegen"},
        {"FIN", "Finnland"},
        {"ICE", "Island"},
        {"GOT", "Gotland"},
        {"KAL", "Kalmar-Union"},

        // Ost-Europa
        {"POL", "Polen"},
        {"LIT", "Litauen"},
        {"PLC", "Polen-Litauen"},
        {"RUS", "Russland"},
        {"MOS", "Moskau"},
        {"NOV", "Nowgorod"},
        {"TVE", "Twer"},
        {"RYA", "Rjasan"},
        {"PSK", "Pskow"},
        {"SMO", "Smolensk"},
        {"YAR", "Jaroslawl"},
        {"HUN", "Ungarn"},
        {"CRO", "Kroatien"},
        {"SER", "Serbien"},
        {"BOS", "Bosnien"},
        {"MOL", "Moldawien"},
        {"WAL", "Walachei"},
        {"TRA", "Siebenbürgen"},
        {"BUL", "Bulgarien"},
        {"ALB", "Albanien"},
        {"GRE", "Griechenland"},
        {"EPI", "Epirus"},
        {"ACH", "Achaia"},
        {"ATH", "Athen"},
        {"BYZ", "Byzanz"},
        {"TRE", "Trapezunt"},

        // Osmanisches Reich & Naher Osten
        {"OTT", "Osmanisches Reich"},
        {"TUN", "Tunesien"},
        {"TRP", "Tripolis"},
        {"KAR", "Karamaniden"},
        {"EGY", "Ägypten"},
        {"MAM", "Mamelucken"},
        {"CYP", "Zypern"},
        {"JER", "Jerusalem"},
        {"ARM", "Armenien"},
        {"GEO", "Georgien"},
        {"PER", "Persien"},
        {"YEM", "Jemen"},
        {"OMA", "Oman"},
        {"HED", "Hedschas"},
        {"ADE", "Aden"},

        // Zentralasien
        {"TIM", "Timuriden"},
        {"UZB", "Usbekistan"},
        {"KAZ", "Kasachstan"},
        {"KHI", "Chiwa"},
        {"CRI", "Krim-Khanat"},
        {"NOG", "Nogaier"},
        {"SHI", "Schirwan"},
        {"QAR", "Kara Koyunlu"},
        {"AQQ", "Ak Koyunlu"},

        // Indien
        {"DLH", "Delhi"},
        {"BHM", "Bahmani"},
        {"VIJ", "Vijayanagar"},
        {"MLW", "Malwa"},
        {"JNP", "Jaunpur"},
        {"GUJ", "Gujarat"},
        {"BNG", "Bengalen"},
        {"ORI", "Orissa"},
        {"MYS", "Mysore"},
        {"KOC", "Kochi"},
        {"KSH", "Kaschmir"},
        {"MUL", "Multan"},
        {"SND", "Sindh"},
        {"KAB", "Kabul"},
        {"MUG", "Mogulreich"},
        {"DEC", "Dekkan"},
        {"BER", "Berar"},
        {"GON", "Gondwana"},
        {"RJP", "Rajputana"},
        {"NEP", "Nepal"},
        {"BTN", "Bhutan"},

        // Südostasien
        {"MAJ", "Majapahit"},
        {"SUN", "Sunda"},
        {"MLK", "Malakka"},
        {"AYU", "Ayutthaya"},
        {"LAN", "Lan Na"},
        {"LNX", "Lan Xang"},
        {"KHM", "Khmer"},
        {"DAI", "Dai Viet"},
        {"ARK", "Arakan"},
        {"PEG", "Pegu"},
        {"AVA", "Ava"},
        {"MDV", "Malediven"},
        {"CEY", "Ceylon"},
        {"BRU", "Brunei"},
        {"JOH", "Johor"},
        {"ACE", "Aceh"},
        {"TER", "Ternate"},
        {"TID", "Tidore"},

        // China & Ostasien
        {"MNG", "Ming-China"},
        {"MCH", "Mandschurei"},
        {"JPN", "Japan"},
        {"KOR", "Korea"},
        {"MON", "Mongolei"},
        {"OIR", "Oirat"},
        {"RYU", "Ryūkyū"},

        // Afrika
        {"MAR", "Marokko"},
        {"FEZ", "Fes"},
        {"TLE", "Tlemcen"},
        {"ETH", "Äthiopien"},
        {"SOM", "Somalia"},
        {"ADA", "Adal"},
        {"KON", "Kongo"},
        {"BEN", "Benin"},
        {"SON", "Songhai"},
        {"MLI", "Mali"},
        {"MSS", "Mossi"},
        {"KAN", "Kanem-Bornu"},
        {"HAU", "Hausa"},
        {"ZIM", "Simbabwe"},
        {"KIL", "Kilwa"},
        {"MOM", "Mombasa"},
        {"OYO", "Oyo"},
        {"ASH", "Ashanti"},
        {"DAH", "Dahomey"},
        {"FUN", "Funj"},
        {"SNG", "Senegal"},

        // Amerika
        {"AZT", "Azteken"},
        {"INC", "Inkareich"},
        {"MAY", "Maya"},
        {"TLX", "Tlaxcala"},
        {"TAR", "Tarasken"},
        {"CHL", "Chile"},
        {"ARG", "Argentinien"},
        {"BRZ", "Brasilien"},
        {"VNZ", "Venezuela"},
        {"PEU", "Peru"},
        {"BOL", "Bolivien"},
        {"PAR", "Paraguay"},
        {"URU", "Uruguay"},
        {"MEX", "Mexiko"},

        // Kaukasus
        {"KAK", "Kakheti"},
        {"IME", "Imereti"},
        {"SAM", "Samtskhe"},
        {"SHK", "Scheki"},
        {"QUB", "Quba"},

        // Weitere
        {"TEU", "Deutschorden"},
        {"LIV", "Livländischer Orden"},
        {"HAN", "Hannover"},
        {"KLE", "Kleve"},
        {"PIE", "Piemont"},
        {"PPA", "Parma"},
        {"EST", "Estland"},
        {"LAT", "Lettland"},
        {"CUR", "Kurland"},
        {"MAZ", "Masowien"},
        {"POD", "Podolien"},
        {"VOL", "Wolhynien"},
        {"UKR", "Ukraine"},
        {"COS", "Kosaken"},
        {"KAS", "Kasan"},
        {"AST", "Astrachan"},
        {"SIB", "Sibirien"},
        {"LEO", "León"},
        {"GAL", "Galicien"},
        {"VAL", "Valencia"},
        {"AND", "Andalusien"},
        {"CHA", "Chagatai"},
        {"MSC", "Mossi-Stämme"},
        {"SCA", "Skandinavien"},
        {"ZAP", "Zapoteken"},
        {"KNI", "Kreuzritter"},
        {"SHL", "Schleswig"},
        {"LTG", "Livland"},
        {"KRL", "Karelien"},
        {"LVA", "Lettland-Livland"},
        {"SMI", "Smolensker Fürstentum"},
        {"GOG", "Gog"},
    };
}
